image: "ubuntu:18.10"

test:
  before_script:
  - apt-get update -yqq
  - apt-get install -yqq build-essential cmake clang-format clang-tidy
  - apt-get install -yqq libmsgpack-dev libpcap-dev librdkafka-dev libhyperscan-dev libgtest-dev
  script:
  - if [ `find src tests \( -name \*.c -o -name \*.cpp -o -name \*.h \) | xargs clang-format -output-replacements-xml | grep -c "<replacement "` -ne "0" ]; then echo "Run clang-format." && false; fi
  - mkdir build && cd build
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - make VERBOSE=1
  - make test
  - clang-tidy -p=. ../src/*.cpp
