[package]
name = "reproduce"
version = "0.12.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1.3"
byteorder = "1.3"
bytesize = "1"
chrono = "0.4"
clap = { version = "4.0", features = ["wrap_help"] }
csv = "1.1"
ctrlc = { version = "3", features = ["termination"] }
eventio = "0.7"
futures = "0.3"
kafka = { version = "0.9", default-features = false }
num_enum = "0.5"
num-traits = "0.2"
quinn = "0.9"
regex = "1"
rmp-serde = "1.1"
rustls = "0.20"
rustls-pemfile = "1.0"
serde = "1"
serde_bytes = "0.11"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.5"
walkdir = "2"
