[package]
name = "reproduce"
version = "0.14.0"
edition = "2021"

[dependencies]
anyhow = "1"
bincode = "1.3"
bytesize = "1"
chrono = "0.4"
clap = { version = "4.2", features = ["wrap_help"] }
csv = "1.2"
ctrlc = { version = "3", features = ["termination"] }
giganto-client = { git = "https://github.com/aicers/giganto-client.git", tag = "0.3.0" }
lazy_static = "1.4"
num-traits = "0.2"
quinn = "0.9"
regex = "1"
rustls = "0.20"
rustls-pemfile = "1.0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2"
