[package]
name = "reproduce"
version = "0.10.0"
edition = "2018"

[dependencies]
anyhow = "1"
byteorder = "1.3"
bytesize = "1"
chrono = "0.4"
clap = { version = "3.2", features = ["wrap_help"] }
ctrlc = { version = "3", features = ["termination"] }
eventio = "0.7"
kafka = { version = "0.9", default-features = false }
quinn = "0.8"
regex = "1"
rmp-serde = "1.1"
rustls = "0.20"
rustls-pemfile = "1.0"
serde = "1"
serde_bytes = "0.11"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "0.5"
walkdir = "2"
