name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: sudo apt-get install libhyperscan-dev libpcap-dev
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v5
      - name: Check formatting
        run: cargo fmt -- --check --config group_imports=StdExternalCrate
      - name: Clippy
        run: cargo clippy --tests -- -D warnings
      - name: Detect Cargo.lock changes
        run: git diff-index --quiet HEAD --
      - name: markdownlint
        uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: sudo apt-get install libhyperscan-dev libpcap-dev
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install libraries
        run: sudo apt-get install libhyperscan-dev libpcap-dev
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v5
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin --version 0.18.0-alpha3
      - name: Generate coverage report
        run: cargo tarpaulin --out xml --avoid-cfg-tarpaulin
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
